package com.stellana.mixing.domain;

public enum BatchStatus {
    PLANNED,
    WAITING_FOR_MATERIALS,
    MATERIALS_REQUESTED,
    MATERIALS_ISSUED,
    READY_FOR_STAGE_1,
    STAGE_1_IN_PROGRESS,
    STAGE_1_COMPLETED,
    READY_FOR_STAGE_2,
    STAGE_2_IN_PROGRESS,
    STAGE_2_COMPLETED,
    SAMPLE_SENT_TO_LAB,
    WAITING_FOR_LAB,
    LAB_PASSED,
    LAB_FAILED,
    ON_HOLD,
    RETEST_REQUIRED,
    REPROCESSING,
    RELEASED_TO_BLANKING,
    STOPPED,
    CANCELLED
}

