package com.stellana.mixing.domain;

public enum InventoryTransactionType {
    COMPOUND_RECEIVED,
    COMPOUND_RESERVED,
    COMPOUND_CONSUMED,
    COMPOUND_RETURNED,
    BLANKS_PRODUCED,
    BLANKS_RESERVED_TO_CART,
    CART_DISPATCHED,
    CART_RECEIVED,
    BLANKS_CONSUMED,
    BLANKS_REJECTED,
    RETURN_RESERVED,
    RETURN_SENT,
    RETURN_CONFIRMED,
    INVENTORY_CORRECTION
}
