package com.stellana.mixing.domain;

public enum Role {
    MANAGER,
    MIXING_OFFICER,
    SYSTEM_ADMIN,
    STORES_OFFICER,
    LAB_OFFICER,
    BLANKING_OPERATOR,
    BLANKING_SUPERVISOR,
    MOULDING_OPERATOR,
    MOULDING_SUPERVISOR
}
