spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stellana_mixing}
    username: ${DB_USERNAME:stellana}
    password: ${DB_PASSWORD:stellana_dev}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

